import type { MultiAgentResearchCouncilReport, PaperTradeBudgetPlan } from './multiAgentResearchCouncil';
import { canonicalPaperTradePlans, fingerprintPaperTradePlans } from './paperTradePlanIntegrity';

export interface PaperPlanReceipt {
  councilFingerprint: string;
  planFingerprint: string;
  createdAt: number;
  expiresAt: number;
}

interface StoredCouncil {
  receipt: PaperPlanReceipt;
  plansCanonical: ReturnType<typeof canonicalPaperTradePlans>;
}

/**
 * Short-lived server-side provenance store. A valid-looking SHA supplied by the
 * browser is not enough: sizing must reference a council result generated by
 * this process and the exact immutable plan set produced by that council.
 */
export class MultiAgentCouncilStore {
  private readonly rows = new Map<string, StoredCouncil>();

  constructor(private readonly ttlMs = 10 * 60_000, private readonly maxEntries = 64) {}

  put(report: MultiAgentResearchCouncilReport, now = Date.now()): PaperPlanReceipt {
    if (report.safety.researchOnly !== true || report.safety.paperOnly !== true || report.safety.executionAuthorized !== false) {
      throw new Error('unsafe_council_report');
    }
    this.prune(now);
    const planFingerprint = fingerprintPaperTradePlans(report.paperTradePlan);
    const receipt: PaperPlanReceipt = {
      councilFingerprint: report.deterministicFingerprint,
      planFingerprint,
      createdAt: now,
      expiresAt: now + this.ttlMs,
    };
    this.rows.set(receipt.councilFingerprint, {
      receipt,
      plansCanonical: canonicalPaperTradePlans(report.paperTradePlan),
    });
    while (this.rows.size > this.maxEntries) {
      const oldest = [...this.rows.entries()].sort((a, b) => a[1].receipt.createdAt - b[1].receipt.createdAt)[0];
      if (!oldest) break;
      this.rows.delete(oldest[0]);
    }
    return { ...receipt };
  }

  verify(councilFingerprint: string, plans: readonly PaperTradeBudgetPlan[], now = Date.now()): PaperPlanReceipt {
    this.prune(now);
    const stored = this.rows.get(councilFingerprint);
    if (!stored) throw new Error('paper_multi_trade_council_receipt_missing_or_expired');
    const incomingFingerprint = fingerprintPaperTradePlans(plans);
    if (incomingFingerprint !== stored.receipt.planFingerprint) throw new Error('paper_multi_trade_plan_fingerprint_mismatch');
    const incomingCanonical = canonicalPaperTradePlans(plans);
    if (JSON.stringify(incomingCanonical) !== JSON.stringify(stored.plansCanonical)) throw new Error('paper_multi_trade_plan_set_mismatch');
    return { ...stored.receipt };
  }

  private prune(now: number) {
    for (const [key, row] of this.rows) if (row.receipt.expiresAt <= now) this.rows.delete(key);
  }
}
