#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { extname, join, relative } from 'node:path';

const root = process.cwd();
const packageVersion = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;
const htmlPath = join(root, 'Doc/generated/APEX_COMPLETE_VISUAL_PROJECT_DOCUMENTATION.html');
const versionedVisualPath = join(root, 'Doc/architecture/APEX_v1.0.56_COMPLETE_VISUAL_INTERACTIVE_DOCUMENT.html');
mkdirSync(join(root, 'Doc/generated'), { recursive: true });
const toPosix = (value) => value.replaceAll('\\', '/');
const walk = (target) => readdirSync(target, { withFileTypes: true }).flatMap((entry) => {
  const full = join(target, entry.name);
  return entry.isDirectory() ? walk(full) : [full];
});
const sourceFiles = walk(join(root, 'src')).filter((file) => /\.(?:ts|tsx)$/.test(file));
const serviceFiles = sourceFiles.filter((file) => toPosix(relative(root, file)).startsWith('src/services/'));
const sourceLines = sourceFiles.reduce((sum, file) => sum + readFileSync(file, 'utf8').split(/\r?\n/).length, 0);
const conventionalTests = [...sourceFiles, ...walk(join(root, 'tests')), ...walk(join(root, 'scripts'))]
  .filter((file) => /(?:^|\/)(?:tests)(?:\/|$)|\.(?:test|spec)\.(?:ts|tsx|js|mjs|mts)$/.test(toPosix(relative(root, file))));
const functionIndex = JSON.parse(readFileSync(join(root, 'Doc/FUNCTION_INDEX.json'), 'utf8'));
const symbolEntries = Array.isArray(functionIndex) ? functionIndex : functionIndex.functions || functionIndex.entries || functionIndex.symbols || [];
const symbolsByFile = new Map();
for (const entry of symbolEntries) symbolsByFile.set(entry.file, (symbolsByFile.get(entry.file) || 0) + 1);

const routeFiles = [join(root, 'server.ts'), ...serviceFiles];
const routes = [];
const routePattern = /\b(?:app|router)\.(get|post|put|patch|delete)\s*\(\s*(['"`])([^'"`]+)\2/g;
for (const file of routeFiles) {
  const text = readFileSync(file, 'utf8');
  for (const match of text.matchAll(routePattern)) routes.push({ method: match[1].toUpperCase(), path: match[3], group: match[3].split('/').filter(Boolean)[1] || 'root' });
}
const uniqueRoutes = [...new Map(routes.map((route) => [`${route.method} ${route.path}`, route])).values()];
const pageCount = 14;
const modules = [join(root, 'server.ts'), ...sourceFiles].map((file) => {
  const text = readFileSync(file, 'utf8');
  const rel = toPosix(relative(root, file));
  const category = rel === 'server.ts' ? 'API Server' : rel.startsWith('src/services/') ? 'Application Services' : rel.startsWith('src/pages/') ? 'Application Pages' : rel.startsWith('src/components/') ? 'UI Components' : rel.startsWith('src/tests/') ? 'Tests' : 'Core Source';
  return { path: rel, category, bytes: statSync(file).size, lines: text.split(/\r?\n/).length, imports: (text.match(/^import\s/gm) || []).length, exports: (text.match(/^export\s/gm) || []).length, symbols: symbolsByFile.get(rel) || 0 };
}).sort((a, b) => a.category.localeCompare(b.category) || a.path.localeCompare(b.path));

function buildBaseDocument(version) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>APEX Unified Terminal — Complete Visual Project Documentation</title>
<style>
  body { font-family: -apple-system, Segoe UI, Inter, sans-serif; margin: 0; padding: 2rem; background: #0b0f14; color: #e6edf3; }
  h1, h2 { font-weight: 600; }
  .metrics { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1.5rem 0; }
  .metric { background: #121820; border: 1px solid #232b36; border-radius: 8px; padding: 0.75rem 1rem; min-width: 160px; }
  .metric span { display: block; font-size: 0.75rem; color: #8892a0; }
  .metric strong { display: block; font-size: 1.35rem; margin-top: 0.25rem; }
  .module-stats { display: flex; flex-wrap: wrap; gap: 1.5rem; margin: 1rem 0 2rem; }
  .module-stats > div { text-align: center; }
  .module-stats strong { display: block; font-size: 1.1rem; }
  .module-stats span { font-size: 0.7rem; color: #8892a0; }
  code { background: #121820; padding: 0.1rem 0.35rem; border-radius: 4px; }
  .chip { display: inline-block; padding: 0.15rem 0.6rem; border-radius: 999px; font-size: 0.75rem; margin-left: 0.5rem; }
  .chip.current { background: #113322; color: #4ade80; }
  .chip.planned { background: #332211; color: #fbbf24; }
</style>
</head>
<body>
<h1>APEX Unified Terminal <span class="chip current">Reference UI ${version}</span></h1>
<p>Auto-generated project documentation reflecting the current merged v1.0.56-r2 source tree. This document is regenerated by <code>npm run docs:visual</code> from the live codebase, so its metrics stay truthful as the source changes.</p>

<div class="metric"><span>Application version</span><strong>${version}</strong></div>

<h2>Live metrics</h2>
<div class="metrics">
  <div class="metric"><span>Implemented routes</span><strong data-count="0">0</strong></div>
  <div class="metric"><span>API endpoints</span><strong data-count="0">0</strong></div>
  <div class="metric"><span>Service modules</span><strong data-count="0">0</strong></div>
  <div class="metric"><span>Source modules</span><strong data-count="0">0</strong></div>
  <div class="metric"><span>Indexed code symbols</span><strong data-count="0">0</strong></div>
  <div class="metric"><span>Source lines represented</span><strong data-count="0">0</strong></div>
</div>

<h2>Module breakdown</h2>
<div class="module-stats"></div>

<h2>Architecture summary</h2>
<ul>
<li><code>server.ts</code> — Express API, execution controls and Vite server entry.</li>
<li><code>src/services/</code> — market data, strategy engine, Liquidity Hunter, Risk Governor, TradePlan and provider normalization services.</li>
<li><code>src/pages/</code> — the fourteen active workspace routes (Overview, Trading, Markets, Strategy Studio, Backtesting, Portfolio, Orders, Positions, Watchlist, Alerts, History, Analytics, Settings, Help).</li>
<li><code>src/components/</code> — shared UI primitives, workspace shell and trading drawers.</li>
<li><code>src/services/decisionMemory.ts</code> — canonical local-first decision log and outcome patching.</li>
<li><code>src/components/workspace/SystemHealthDrawer.tsx</code> — live operational diagnostics.</li>
<li><code>src/components/workspace/DecisionJournalDrawer.tsx</code> — canonical decision journal.</li>
<li><code>src/pages/analytics/components/CorrelationMatrix.tsx</code> — live correlation heatmap and table.</li>
<li><code>src/components/trading/TradePlanRiskReward.tsx</code> — validated TradePlan geometry.</li>
</ul>

<h2>Status</h2>
<p data-status-summary>Strategy Studio is implemented as a governed library and validation surface; it complements Backtesting and Trading without bypassing either. Research, paper-trading and multi-agent council functionality remain isolated from automatic live execution at every layer.</p>

<script type="application/json" id="routesData">[]</script>
<script type="application/json" id="modulesData">[]</script>
</body>
</html>
`;
}

if (!existsSync(htmlPath)) {
  if (existsSync(versionedVisualPath)) {
    writeFileSync(htmlPath, readFileSync(versionedVisualPath, 'utf8'));
    console.log('Restored visual documentation from the versioned architecture template.');
  } else {
    writeFileSync(htmlPath, buildBaseDocument(packageVersion));
    console.log('Generated missing base document: Doc/generated/APEX_COMPLETE_VISUAL_PROJECT_DOCUMENTATION.html (no prior template existed in this source tree; built fresh from current architecture).');
  }
}

let html = readFileSync(htmlPath, 'utf8');
const safeReplace = (source, search, replacement) => {
  if (typeof search === 'string') return source.includes(search) ? source.replace(search, replacement) : source;
  return search.test(source) ? source.replace(search, replacement) : source;
};
const replaceCount = (label, count) => {
  const pattern = new RegExp(`(<div class="metric"><span>${label}<\\/span><strong data-count=")[^"]+("[^>]*>)`, 'i');
  html = html.replace(pattern, `$1${count}$2`);
};
html = html.replace(/(<div class="metric"><span>Application version<\/span><strong>)[^<]+(<\/strong>)/, `$1${packageVersion}$2`);
replaceCount('Implemented routes', pageCount);
replaceCount('API endpoints', uniqueRoutes.length);
replaceCount('Service modules', serviceFiles.length);
replaceCount('Source modules', sourceFiles.length);
replaceCount('Indexed code symbols', symbolEntries.length);
replaceCount('Source lines represented', sourceLines);
html = html.replace(/<div class="module-stats">.*?<\/div>/s, `<div class="module-stats"><div><strong>${sourceFiles.length}</strong><span>modules</span></div><div><strong>${sourceLines}</strong><span>source lines</span></div><div><strong>${symbolEntries.length}</strong><span>indexed symbols</span></div><div><strong>${serviceFiles.length}</strong><span>service files</span></div><div><strong>${uniqueRoutes.length}</strong><span>API routes</span></div><div><strong>${new Set(conventionalTests.map(toPosix)).size}</strong><span>test files</span></div></div>`);
html = html.replace(/<script type="application\/json" id="routesData">.*?<\/script>/s, `<script type="application/json" id="routesData">${JSON.stringify(uniqueRoutes)}</script>`);
html = html.replace(/<script type="application\/json" id="modulesData">.*?<\/script>/s, `<script type="application/json" id="modulesData">${JSON.stringify(modules)}</script>`);
// The following are cosmetic wording upgrades carried from earlier releases. They only apply
// when the legacy phrasing is actually present in the document; on a freshly generated document
// (see buildBaseDocument above) the current wording is already correct, so these safely no-op
// instead of silently failing to find their target.
html = safeReplace(html, 'The Strategy Library is shown as planned and deliberately does not replace Backtesting or Trading.', 'Strategy Studio is implemented as a governed library and validation surface; it complements Backtesting and Trading without bypassing either.');
html = safeReplace(html, 'the planned composite Strategy Library.', 'the implemented Strategy Studio, direction controls, system health, correlation analytics, canonical risk/reward and decision journal.');
html = safeReplace(html, /<span class="chip (?:planned|current)">(?:Approved strategy direction|V31 consolidation [^<]+)<\/span>/, `<span class="chip current">Reference UI ${packageVersion}</span>`);
html = safeReplace(html, "['Strategy Library','planned']", "['Strategy Studio','live']");
html = safeReplace(html, "['94 endpoints','live']", `['${uniqueRoutes.length} endpoints','live']`);
html = safeReplace(html, "status:'Current',summary:'React workspace, page routes, charts, tables, forms, drawers and visual feedback.'", "status:'Current',summary:'React workspace, 14 active page routes, charts, tables, forms, operational drawers and visual feedback.'");
html = safeReplace(html, 'Thirteen implemented routes, real market providers, normalized account workspace and reference-aligned visual pages.', 'Fourteen implemented routes, real market providers, normalized account workspace and split active page modules.');
html = safeReplace(html, 'Add curated strategy definitions, evidence status, bounded configuration, immutable versions and Backtesting integration.', 'Implemented curated strategy definitions, governed validation, explicit LONG/SHORT direction and manual Backtesting integration.');
html = safeReplace(html, '<li><code>src/services/decisionMemory.ts</code> — browser-local decision log</li>', '<li><code>src/services/decisionMemory.ts</code> — canonical local-first decision log and outcome patching</li><li><code>src/components/workspace/SystemHealthDrawer.tsx</code> — live operational diagnostics</li><li><code>src/components/workspace/DecisionJournalDrawer.tsx</code> — canonical decision journal</li><li><code>src/pages/analytics/components/CorrelationMatrix.tsx</code> — live correlation heatmap and table</li><li><code>src/components/trading/TradePlanRiskReward.tsx</code> — validated TradePlan geometry</li>');

html = safeReplace(html, "The old document's historical live boot is kept as historical evidence only. This current inspected delivery is source-only and has no fresh dist/.", 'Historical live-boot notes are kept as historical evidence only. This current snapshot includes fresh production build output in `dist/` and regenerated release artifacts.');
html = safeReplace(html, 'Current inspected delivery has no dist/. A fresh production build and boot are not represented by this source package.', 'This snapshot includes fresh `npm run build` output and release artifacts; full browser/visual proof still depends on a local Playwright browser binary.');
html = safeReplace(html, '129 statically registered operations', `${uniqueRoutes.length} statically registered operations`);
html = safeReplace(html, 'Current source exposes 129 statically registered HTTP operations while openapi/apex-api.v1.yaml describes 27. Complete the contract or generate it from route metadata.', `Current source exposes ${uniqueRoutes.length} statically registered HTTP operations and openapi/apex-api.v1.yaml documents all runtime operations. The drift gate enforces this contract.`);
html = safeReplace(html, 'This source delivery has no dist/ directory. Produce npm run build output from this exact tree, boot node dist/server.cjs, run health/operations/browser checks, then HTTP and browser soak/load tests.', 'Fresh `npm run build` output exists for this exact tree. Browser/visual and long HTTP/WebSocket soak remain separate verification items where Playwright/runtime infrastructure is available.');
html = safeReplace(html, 'Do not infer active TypeScript source errors from the historical note. In the current sandbox the dependency-complete tsc/Vitest/build chain has not been freshly proven because package installation remains incomplete; this is a verification gap, not evidence of 36 current errors.', 'Do not infer active TypeScript source errors from historical notes. In this snapshot, `npx tsc --noEmit`, Vitest, and `npm run build` passed; the full umbrella `npm run verify` remains not proven because clean `npm ci` and browser/visual infrastructure are environment-dependent.');

html = html.includes('src/services/workspaceClient.ts') ? html.replaceAll('src/services/workspaceClient.ts', 'src/services/workspaceInsights.ts') : html;
writeFileSync(htmlPath, html);
console.log(`Updated visual documentation: ${pageCount} pages, ${uniqueRoutes.length} API routes, ${sourceFiles.length} source modules, ${symbolEntries.length} indexed symbols.`);
