import React from 'react';
import { AlertTriangle, BookOpen, Clock3, Download, FileDown, Info, ShieldCheck } from 'lucide-react';
import type { BacktestResult, DataState } from '../../types';
import type { BacktestHistoryEntry, BacktestRunConfig } from './backtestingTypes';
import { deriveBacktestCoverage } from './backtestCoverage';

function pct(value: number | null | undefined, digits = 1): string {
  return value == null || !Number.isFinite(value) ? '—' : `${value.toFixed(digits)}%`;
}
function formatTime(value: number): string {
  return new Date(value).toLocaleString(undefined, { month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit' });
}

export function BacktestEvidenceRail({
  result,
  routeDataState,
  config,
  history,
  onExport,
  onOpenHistory,
  onOpenDataQuality,
  onOpenRuntime,
  canExport,
}: {
  result: BacktestResult | null;
  routeDataState: DataState;
  config: BacktestRunConfig;
  history: BacktestHistoryEntry[];
  onExport: () => void;
  onOpenHistory: () => void;
  onOpenDataQuality: () => void;
  onOpenRuntime: () => void;
  canExport: boolean;
}) {
  const coverage = deriveBacktestCoverage(result, config);
  const warnings = [
    coverage.status === 'partial' || coverage.status === 'poor' ? `Partial history (${pct(coverage.coveragePct)} coverage)` : null,
    result?.costModel?.fundingPctEstimate != null ? 'Funding rate estimated' : null,
    result && result.timeline.length === 0 ? (result.diagnostics?.noTradeReason || 'No trades generated by strategy gates') : null,
    routeDataState !== 'live' && !result ? `Market data ${routeDataState.replaceAll('_', ' ')}` : null,
  ].filter(Boolean) as string[];
  return (
    <aside className="apex-bt-studio-rail" aria-label="Backtesting evidence and report rail">
      <section className="apex-bt-rail-card data-quality">
        <header><span>Data Quality</span><button type="button" onClick={onOpenDataQuality}>Details</button></header>
        <dl>
          <div><dt>Data completeness</dt><dd>{coverage.coveragePct == null ? 'Pending' : pct(coverage.coveragePct, coverage.coveragePct >= 99.5 ? 0 : 1)}</dd></div>
          <div><dt>Gaps detected</dt><dd>{coverage.missingCandles.toLocaleString()}</dd></div>
          <div><dt>Executable candles</dt><dd>{result ? coverage.executableCandles.toLocaleString() : '—'}</dd></div>
          <div><dt>Price continuity</dt><dd>{coverage.status === 'full' ? 'Good' : coverage.status === 'pending' ? 'Pending' : 'Review'}</dd></div>
        </dl>
      </section>

      <section className="apex-bt-rail-card assumptions">
        <header><span>Execution Assumptions</span><button type="button" onClick={onOpenRuntime}>Runtime</button></header>
        <dl>
          <div><dt>Order type</dt><dd>{result?.audit?.fillPolicy || 'NEXT_BAR_OR_BRACKET'}</dd></div>
          <div><dt>Commission / side</dt><dd>{pct(result?.costModel?.commissionPctPerSide ?? config.commissionPct, 3)}</dd></div>
          <div><dt>Slippage / side</dt><dd>{pct(result?.costModel?.slippagePctPerSide ?? config.slippagePct, 3)}</dd></div>
          <div><dt>Funding model</dt><dd>{result?.costModel ? 'Estimated' : `${config.fundingPct.toFixed(3)}% configured`}</dd></div>
        </dl>
      </section>

      <section className={`apex-bt-rail-card warnings ${warnings.length ? 'has-warnings' : ''}`}>
        <header><span>Warnings &amp; Limitations</span><strong>{warnings.length ? `${warnings.length}` : 'Clear'}</strong></header>
        {warnings.length ? <ul>{warnings.map((warning) => <li key={warning}><AlertTriangle size={12} aria-hidden="true" />{warning}</li>)}</ul> : <p><ShieldCheck size={13} aria-hidden="true" />No result-specific warnings have been recorded yet.</p>}
      </section>

      <section className="apex-bt-rail-card export">
        <header><span>Export / Save Report</span></header>
        <div className="apex-bt-rail-actions">
          <button type="button" onClick={onExport} disabled={!canExport}><Download size={13} aria-hidden="true" />Export Results</button>
          <button type="button" onClick={onExport} disabled={!canExport}><FileDown size={13} aria-hidden="true" />Save Report</button>
        </div>
        <small>JSON export uses the canonical server result plus separately labelled local calculations.</small>
      </section>

      <section className="apex-bt-rail-card history">
        <header><span>Run History</span><button type="button" onClick={onOpenHistory}>View all</button></header>
        {history.length ? <ol>{history.slice(0, 4).map((entry) => <li key={entry.id}><Clock3 size={12} aria-hidden="true" /><span>{formatTime(entry.timestamp)}<small>{entry.symbol} · {entry.interval}</small></span><b className={entry.netReturnPct >= 0 ? 'positive' : 'negative'}>{entry.netReturnPct >= 0 ? '+' : ''}{entry.netReturnPct.toFixed(2)}%</b></li>)}</ol> : <p><BookOpen size={13} aria-hidden="true" />No saved local run history yet.</p>}
      </section>
    </aside>
  );
}
